# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 489818a32f6c2692423b6b0c8bbe9fc9ec171239b4ccea9f0e6f6f7476d61921ff6c3c30682348c29e9a623690e5e06a664e4eed9ecd3cb13c990a72f6d0b5cf

test:
  secret_key_base: c1680faa58b1fc735b030eb67985def793fcfdbea27a16a99875ca6318f16842aa3a7b149e0a26d92d0e3f7f573c18718b66e261a6fd1cbeb886fd7b8105c8d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
